services:
  user_db:
    image: postgres:latest
    container_name: postgres-database
    ports:
      - "${USER_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${USER_DB_USERNAME}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: ${USER_DB_NAME}
    volumes:
      - user_db:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "${BROKER_PORT}:5672"
      - "${BROKER_MANAGEMENT_PORT}:15672"
    environment:
      #TODO: configure for safety
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  user_db:
  rabbitmq_data:
